### PR TITLE
Fix arrow duplication bug and make multishot more like crossbows

### LINKED ISSUE #1: Arrow duping with multishot bows
Arrows shot from a multishot regular bow can be picked up, multiplying arrows by seven. Additionally, tipped arrows are not consumed upon firing. I've reproduced this in a fresh instance with the mods listed below.

Mod list:
Better Multishot
Fabric API
Lithium
Mod Menu
No Chat Reports
No Telemetry
Sodium
Starlight

Steps to reproduce:

1. get a Multishot bow & arrows
2. fire bow
3. pick up arrows

I screenshotted the bug happening, here are some pictures:
Screenshot_20221129_141731
Screenshot_20221129_141749
Screenshot_20221129_141801

Thanks for this mod, it's a lot of fun to play around with!

### PR DESCRIPTION
**Pull request by OffsetMonkey538**
Should fix #1

### CODE REVIEW

**Comment by OffsetMonkey538** [comment]
It would be nice if someone could test the mod and see if:
1. The arrow duplication bug (#1) is fixed
2. There are any bugs with shooting multishot bows and throwable items.

**Comment by tesseract-two** [comment]
Not sure if this is a bug, but the center (original?) Bottle o' Enchanting seems to have more upwards velocity? This doesn't matter to me, and it lands in around the same spot, but just so you know.

**Comment by OffsetMonkey538** [comment]
Will deal with that, thanks!

**Comment by OffsetMonkey538** [comment]
It should be fixed now. Could you please check with the artifact [here](https://github.com/OffsetMonkey538/Better-Multishot/actions/runs/3832914808)

**Comment by tesseract-two** [comment]
Yup, it's fixed.

**Pull request merged**
